version: 0.2
phases:
 install:
   commands:
     - mv /usr/local/bin/docker /usr/bin/docker
     - curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh
     
 build:
   commands:
     - echo Convert Compose File
     - docker context create ecs myecscontext --from-env
     - docker context use myecscontext
     - docker-compose -f docker-compose.prod.yml convert
     - docker-compose -f docker-compose.prod.yml convert> template.yml
artifacts:
  files:
    - template.yml